server:
  port: 8082
logging:
  level:
    org:
      springframework: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:dbo
    username: user
    password: pass
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

